# Generated by Django 4.1.3 on 2023-03-19 14:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=16)),
                ('difficulty', models.IntegerField(default=1)),
                ('about', ckeditor.fields.RichTextField()),
                ('info_out', models.TextField(blank=True, null=True)),
                ('info_in', models.TextField(blank=True, null=True)),
                ('simple_tests', models.JSONField()),
                ('tests', models.JSONField()),
                ('yechim', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('foiz', models.FloatField(default=0)),
                ('accepteds', models.ManyToManyField(blank=True, null=True, related_name='user_problem_accepted', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='user_problem_like', to=settings.AUTH_USER_MODEL)),
                ('save_users', models.ManyToManyField(blank=True, null=True, related_name='save_problem_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_comment', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
