# Generated by Django 4.1.3 on 2023-03-19 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_problem_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
