# Generated by Django 4.1.3 on 2023-03-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='save_users',
        ),
    ]
