# Generated by Django 4.1.3 on 2023-03-20 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0003_remove_problem_dislikes_remove_problem_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='wrong_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_problem_wrong_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
