# Generated by Django 4.2.4 on 2023-08-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_wrong_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='simple_tests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
