# Generated by Django 4.1.3 on 2023-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fan',
            field=models.CharField(blank=True, choices=[('math', 'Matematika'), ('ona_tili', 'Ona Tili'), ('musiqa', 'Musiqa'), ('rus_tili', 'Rus tili'), ('english', 'Chet tili'), ('j_tar', 'Jismoniy tarbiya'), ('tarix', 'Tasrix'), ('geografiya', 'Geografiya'), ('tasvir', "Tasviriy san'at"), ('informatika', 'Informatika'), ('direktor', 'Direktor'), ('urin_bosar', "Direktor o'rin bosari"), ('psixolog', 'Psixolog'), ('maslahatchi', 'Maslahatchi'), ('chqbt', 'Chqbt'), ('kitob', 'Kutubxona'), ('biologiya', 'Biologiya'), ('kimyo', 'Kimyo'), ('huquq', 'Huquq'), ('fizika', 'Fizika'), ('texnologiya', 'Texnologiya'), ('iqtisod', 'Iqtisod')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sinf',
            field=models.CharField(blank=True, choices=[('51', '5.1'), ('52', '5.2'), ('61', '6.1'), ('62', '6.2'), ('71', '7.1'), ('72', '7.2'), ('73', '7.3'), ('81', '8.1'), ('82', '8.2'), ('83', '8.3'), ('91', '9.1'), ('92', '9.2'), ('93', '9.3'), ('101', '10.1'), ('102', '10.2'), ('103', '10.3'), ('111', '11.1'), ('112', '11.2'), ('113', '11.3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='theme',
            field=models.CharField(choices=[('default', 'dark'), ('light', 'light')], default='light', max_length=30),
        ),
    ]
