# Generated by Django 4.1.3 on 2023-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fan',
            field=models.CharField(blank=True, choices=[('Matematika', 'Matematika'), ('ona_tili', 'Ona Tili'), ('musiqa', 'Musiqa'), ('rus_tili', 'Rus tili'), ('english', 'Chet tili'), ('jismoniy_tarbiya', 'Jismoniy tarbiya'), ('tarix', 'Tarix'), ('geografiya', 'Geografiya'), ('tasviriy_sanat', "Tasviriy san'at"), ('informatika', 'Informatika'), ('direktor', 'Direktor'), ('urin_bosar', "Direktor o'rin bosari"), ('psixolog', 'Psixolog'), ('maslahatchi', 'Maslahatchi'), ('chqbt', 'Chqbt'), ('kutubxonaxhi', 'Kutubxona'), ('biologiya', 'Biologiya'), ('kimyo', 'Kimyo'), ('huquq', 'Huquq'), ('fizika', 'Fizika'), ('texnologiya', 'Texnologiya'), ('iqtisod', 'Iqtisod')], max_length=30, null=True),
        ),
    ]
