# Generated by Django 4.1.3 on 2023-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ball',
            field=models.FloatField(default=0.0),
        ),
    ]
