# Generated by Django 4.1.3 on 2023-04-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_myuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='navbar_color',
            field=models.CharField(choices=[('light', 'light'), ('blue', 'blue'), ('green', 'green'), ('brown', 'brown'), ('black', 'black')], default='blue', max_length=30),
        ),
    ]
