# Generated by Django 4.1.3 on 2023-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_myuser_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='font',
            field=models.CharField(choices=[('Ysabeau', 'Ysabeau'), ('Poltawski Nowy', 'Poltawski Nowy'), ('Instrument Serif', 'Instrument Serif'), ('Josefin Sans', 'Josefin Sans'), ('Rajdhani', 'Rajdhani'), ('sans-serif', 'sans-serif')], default='sans-serif', max_length=30),
        ),
    ]
