# Generated by Django 4.1.3 on 2023-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_myuser_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sinf',
            field=models.CharField(blank=True, choices=[('5.1', '5.1'), ('5.2', '5.2'), ('6.1', '6.1'), ('6.2', '6.2'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3'), ('11.1', '11.1'), ('11.2', '11.2'), ('11.3', '11.3'), ('Guest', 'Guest')], max_length=30, null=True),
        ),
    ]
