# Generated by Django 4.1.3 on 2023-05-05 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_myuser_sinf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends_1', to=settings.AUTH_USER_MODEL),
        ),
    ]
