# Generated by Django 4.1.3 on 2023-05-05 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_myuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
