# Generated by Django 4.1.3 on 2023-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_myuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
