# Generated by Django 4.2.4 on 2023-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_myuser_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='api_token',
            field=models.CharField(default='', max_length=90),
        ),
    ]
