# Generated by Django 4.2.4 on 2023-11-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_myuser_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('Xato', 'Xato'), ('Muvoffiqiyat', 'Muvoffiqiyat'), ('Qurilma', 'Qurilma'), ('Ball', 'Ball'), ('Topshiriq', 'Topshiriq'), ('Kurs', 'Kurs')], max_length=40)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
