# Generated by Django 4.2.4 on 2023-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_myuser_api_token_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_create_ass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_create_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_create_masala',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_create_test',
            field=models.BooleanField(default=False),
        ),
    ]
