# Generated by Django 4.2.4 on 2023-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_myuser_is_create_ass_myuser_is_create_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_create_bsb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_create_yechim',
            field=models.BooleanField(default=False),
        ),
    ]
