# Generated by Django 4.1.3 on 2023-05-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0003_chat_last_message_text_alter_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_chat', to='my_messages.message'),
        ),
    ]
