# Generated by Django 4.2.4 on 2023-08-13 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='courses.coursetag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
