# Generated by Django 4.2.4 on 2023-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_tags_alter_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
