# Generated by Django 4.2.4 on 2023-08-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessons_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemultiquiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multi_quizess', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quizess', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseyopiqtest',
            name='lesson',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='yopiq_tests', to='courses.lessons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draganddropquiz',
            name='course',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='drag_and_drop_quizes', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectures',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course'),
            preserve_default=False,
        ),
    ]
