# Generated by Django 4.2.4 on 2023-08-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursemultiquiz_course_coursequiz_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='courses.lessons'),
        ),
    ]
