# Generated by Django 4.2.4 on 2023-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_multiquizanswer_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemultiquiz',
            name='slug',
            field=models.SlugField(default='asfdf'),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='slug',
            field=models.SlugField(default='asfdf'),
        ),
        migrations.AddField(
            model_name='courseyopiqtest',
            name='slug',
            field=models.SlugField(default='asfdf'),
        ),
        migrations.AddField(
            model_name='draganddropquiz',
            name='slug',
            field=models.SlugField(default='asfdf'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='slug',
            field=models.SlugField(default='asfdf'),
        ),
    ]
