# Generated by Django 4.2.4 on 2023-08-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursemultiquiz_slug_coursequiz_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.coursequizvariant'),
            preserve_default=False,
        ),
    ]
