# Generated by Django 4.2.4 on 2023-08-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_yopiqtestvariants_yopiqtestanswer_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yopiqtestanswer',
            name='answer',
        ),
    ]
