# Generated by Django 4.2.4 on 2023-08-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_yopiqtestanswer_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yopiqtestanswer',
            name='answer',
            field=models.CharField(default=1, max_length=324234235423),
            preserve_default=False,
        ),
    ]
