# Generated by Django 4.2.4 on 2023-08-14 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_yopiqtestanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='draganddropquiz',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
