# Generated by Django 4.2.4 on 2023-08-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_multiquizanswer_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiquizanswer',
            name='variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.multiquizvariuant'),
        ),
    ]
