# Generated by Django 4.2.4 on 2023-08-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_multiquizanswer_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiquizanswer',
            name='variants',
        ),
        migrations.AddField(
            model_name='multiquizanswer',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='courses.multiquizvariuant'),
        ),
    ]
