# Generated by Django 4.1.3 on 2023-04-03 14:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinflar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_statrted', models.DateTimeField()),
                ('date_ended', models.DateTimeField()),
                ('holati', models.CharField(max_length=20)),
                ('body', ckeditor.fields.RichTextField()),
                ('actioned_users', models.ManyToManyField(related_name='user_action_BSB', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_BSB', to=settings.AUTH_USER_MODEL)),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinf_BSBs', to='sinflar.sinf')),
            ],
        ),
        migrations.CreateModel(
            name='BsbTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('date_sended', models.DateTimeField(auto_now_add=True)),
                ('bsb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_tasks', to='bsb.bsb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BsbBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urin', models.IntegerField()),
                ('ball', models.FloatField()),
                ('bsb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_bsbs', to='bsb.bsb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
