# Generated by Django 4.1.3 on 2023-04-03 15:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bsbtask',
            old_name='date_sended',
            new_name='date_created',
        ),
        migrations.CreateModel(
            name='BsbAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('date_sended', models.DateTimeField(auto_now_add=True)),
                ('bsb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_answer', to='bsb.bsb')),
                ('bsb_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_task_answer', to='bsb.bsbtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_answer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
