# Generated by Django 4.1.3 on 2023-04-03 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsb', '0002_rename_date_sended_bsbtask_date_created_bsbanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsb',
            name='actioned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_action_BSB', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bsb',
            name='holati',
            field=models.CharField(default='Boshlanmagan', max_length=20),
        ),
    ]
