# Generated by Django 4.1.3 on 2023-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0003_alter_bsb_actioned_users_alter_bsb_holati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsb',
            name='holati',
            field=models.CharField(blank=True, choices=[('Tugagan', 'Tugagan'), ('Boshlanmagan', 'Boshlanmagan'), ('Dovom etmoqda', 'Dovom etmoqda')], default='Boshlanmagan', max_length=20, null=True),
        ),
    ]
