# Generated by Django 4.1.3 on 2023-04-04 15:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsb', '0005_bsb_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsbProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=16)),
                ('difficulty', models.IntegerField(default=1)),
                ('about', ckeditor.fields.RichTextField()),
                ('info_out', models.TextField(blank=True, null=True)),
                ('info_in', models.TextField(blank=True, null=True)),
                ('simple_tests', models.JSONField()),
                ('tests', models.JSONField()),
                ('yechim', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('foiz', models.FloatField(default=0)),
                ('ball', models.FloatField()),
                ('accepteds', models.ManyToManyField(blank=True, null=True, related_name='accepted_problems', to=settings.AUTH_USER_MODEL)),
                ('bsb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='bsb.bsb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_problems', to=settings.AUTH_USER_MODEL)),
                ('wrong_answers', models.ManyToManyField(blank=True, null=True, related_name='wrong_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BsbProblemBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.FloatField()),
                ('bsb_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='bsb.bsbproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_problem_balls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bsbball',
            name='bsb',
        ),
        migrations.RemoveField(
            model_name='bsbball',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bsbtask',
            name='bsb',
        ),
        migrations.RemoveField(
            model_name='bsbtask',
            name='user',
        ),
        migrations.DeleteModel(
            name='BsbAnswer',
        ),
        migrations.DeleteModel(
            name='BsbBall',
        ),
        migrations.DeleteModel(
            name='BsbTask',
        ),
    ]
