# Generated by Django 4.1.3 on 2023-04-04 16:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsb', '0008_bsbassignment_studentanswer_studentanswerball'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsbQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(default=0)),
                ('body', ckeditor.fields.RichTextField()),
                ('ball', models.FloatField()),
                ('bsb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizess', to='bsb.bsb')),
            ],
        ),
        migrations.AddField(
            model_name='bsbassignment',
            name='ball',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BsbQuizTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='bsb.bsbquiz')),
            ],
        ),
        migrations.CreateModel(
            name='BsbQuizBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.FloatField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_quiz_ball', to='bsb.bsb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsb_quiz_ball', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
