# Generated by Django 4.1.3 on 2023-04-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0012_alter_bsbquizball_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsbquizball',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='bsb.bsb'),
        ),
    ]
