# Generated by Django 4.1.3 on 2023-04-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0015_bsbquizball_quizess_delete_bsbquizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsbproblemball',
            name='bsb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_balls', to='bsb.bsb'),
        ),
    ]
