# Generated by Django 4.1.3 on 2023-04-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0016_bsbproblemball_bsb'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerball',
            name='bsb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_balls', to='bsb.bsb'),
            preserve_default=False,
        ),
    ]
