# Generated by Django 4.1.3 on 2023-04-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0017_studentanswerball_bsb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsbproblemball',
            name='bsb',
        ),
    ]
