# Generated by Django 4.1.3 on 2023-04-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0018_remove_bsbproblemball_bsb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsb',
            name='problem_ball',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
