# Generated by Django 4.1.3 on 2023-04-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0019_bsb_problem_ball'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsb',
            name='problem_ball',
        ),
    ]
