# Generated by Django 4.1.3 on 2023-04-25 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsb', '0021_yakuniy'),
    ]

    operations = [
        migrations.AddField(
            model_name='yakuniy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yakuniy_baho_contorls', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
