# Generated by Django 4.1.3 on 2023-04-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0022_yakuniy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='yakuniy',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yakuniy_ball', to='bsb.bsbassignment'),
        ),
        migrations.AddField(
            model_name='yakuniy',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yakuniy_balls', to='bsb.bsbassignment'),
        ),
    ]
