# Generated by Django 4.1.3 on 2023-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0023_yakuniy_assignment_yakuniy_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yakuniy',
            name='assignment',
        ),
        migrations.AddField(
            model_name='yakuniy',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, related_name='yakuniy_ball', to='bsb.bsbassignment'),
        ),
        migrations.RemoveField(
            model_name='yakuniy',
            name='problem',
        ),
        migrations.AddField(
            model_name='yakuniy',
            name='problem',
            field=models.ManyToManyField(blank=True, null=True, related_name='yakuniy_balls', to='bsb.bsbassignment'),
        ),
    ]
