# Generated by Django 4.1.3 on 2023-04-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0024_remove_yakuniy_assignment_yakuniy_assignments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yakuniy',
            name='ball',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
