# Generated by Django 4.1.3 on 2023-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0025_alter_yakuniy_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yakuniy',
            name='problem',
            field=models.ManyToManyField(blank=True, null=True, related_name='yakuniy_balls', to='bsb.bsbproblem'),
        ),
    ]
