# Generated by Django 4.0.6 on 2023-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0026_alter_yakuniy_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsb',
            name='quizes',
            field=models.ManyToManyField(related_name='bsblar', to='bsb.bsbquiz'),
        ),
    ]
