# Generated by Django 4.0.6 on 2023-11-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsb', '0027_bsb_quizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsb',
            name='quizes',
        ),
    ]
