# Generated by Django 4.1.3 on 2023-03-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_studentanswerballcomment_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sinf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
