# Generated by Django 4.1.3 on 2023-03-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_sinf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='fan',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswerball',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
