# Generated by Django 4.0.6 on 2023-11-04 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0005_alter_studentanswer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='javoblar',
            field=models.ManyToManyField(blank=True, null=True, related_name='topshirilgan_topshiriqlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
