# Generated by Django 4.0.6 on 2023-11-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_javoblar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerball',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigment_answer_balls', to='assignments.assignment'),
            preserve_default=False,
        ),
    ]
