# Generated by Django 4.2.4 on 2023-11-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignmentreaded'),
        ('assignments', '0007_studentanswerball_assignment'),
    ]

    operations = [
    ]
