# Generated by Django 4.2.4 on 2023-11-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_merge_20231107_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentReaded',
        ),
    ]
