# Generated by Django 4.2.4 on 2023-11-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('ball', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('true_answer', models.CharField(max_length=100000000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_closed_quizes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefoulMultitQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('ball', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_multi_quizes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefoultQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('ball', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_quizes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('ball', models.FloatField(default=0.0)),
                ('actiened_users', models.ManyToManyField(blank=True, null=True, related_name='drag_and_drop_quizess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('time', models.TimeField()),
                ('summary', models.TextField()),
                ('type', models.CharField(choices=[('Oson', 'Oson'), ("O'rtacha", "O'rtacha"), ('Qiyin', 'Qiyin'), ('Juda Qiyin', 'Juda Qiyin')], max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('quizes_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_test', to=settings.AUTH_USER_MODEL)),
                ('not_actioned_users', models.ManyToManyField(related_name='tasks_not_actioned', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('started_time', models.TimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strted_time', to='quizess.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_time_in_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('orin', models.IntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quizess.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDropVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='quizess.draganddropvariants')),
                ('quiz_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizess.draganddrop')),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDropAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=99999999999999)),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dad_answer', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_and_drop_answers', to='quizess.quiz')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quizess.draganddrop')),
            ],
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_and_drop', to='quizess.quiz'),
        ),
        migrations.CreateModel(
            name='DefoultQuizVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('default_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizess.defoultquiz')),
            ],
        ),
        migrations.AddField(
            model_name='defoultquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_quizes', to='quizess.quiz'),
        ),
        migrations.AddField(
            model_name='defoultquiz',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted_quizess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DefoulMultitQuizVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('default_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizess.defoulmultitquiz')),
            ],
        ),
        migrations.CreateModel(
            name='DefoulMultitQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('default_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizess.defoulmultitquiz')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_multi_quiz_answers', to='quizess.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_answer_default_multi_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='defoulmultitquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_multi_quizes', to='quizess.quiz'),
        ),
        migrations.AddField(
            model_name='defoulmultitquiz',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted_multi_quizess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DefaultQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('default_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizess.defoultquiz')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_quiz_answers', to='quizess.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_answer_default_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=3234234234)),
                ('closed_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizess.closedtest')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_closed_answers', to='quizess.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_test_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='closedtest',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_closed_quizes', to='quizess.quiz'),
        ),
        migrations.AddField(
            model_name='closedtest',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted_closed_quizess', to=settings.AUTH_USER_MODEL),
        ),
    ]
