# Generated by Django 4.2.4 on 2023-08-26 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DragAndDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('actiened_users', models.ManyToManyField(blank=True, null=True, related_name='drag_and_drop_quizess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('time', models.TimeField()),
                ('summary', models.TextField()),
                ('type', models.CharField(choices=[('Oson', 'Oson'), ("O'rtacha", "O'rtacha"), ('Qiyin', 'Qiyin'), ('Juda Qiyin', 'Juda Qiyin')], max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('quizes_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_test', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDropVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='quizess.draganddropvariants')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizess.draganddrop')),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDropAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=99999999999999)),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dad_answer', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_and_drop_answers', to='quizess.quiz')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quizess.draganddrop')),
            ],
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_and_drop', to='quizess.quiz'),
        ),
    ]
