# Generated by Django 4.1.3 on 2023-03-12 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actioned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='actioned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
