# Generated by Django 4.2.4 on 2023-08-26 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizess', '0002_defoultquiz_defoultquizvariant_defaultquizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defoultquiz',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted_quizess', to=settings.AUTH_USER_MODEL),
        ),
    ]
