# Generated by Django 4.2.4 on 2023-08-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizess', '0003_alter_defoultquiz_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draganddropvariants',
            old_name='quiz',
            new_name='quiz_dr',
        ),
    ]
