# Generated by Django 4.2.4 on 2023-08-27 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizess', '0004_rename_quiz_draganddropvariants_quiz_dr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefoulMultitQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('ball', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_multi_uizes', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_multi_quizes', to='quizess.quiz')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='accepted_multi_quizess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='defoultquiz',
            name='ball',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='ball',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DefoulMultitQuizVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('default_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizess.defoulmultitquiz')),
            ],
        ),
        migrations.CreateModel(
            name='DefoulMultitQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('default_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizess.defoulmultitquiz')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_multi_quiz_answers', to='quizess.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_answer_default_multi_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
