# Generated by Django 4.2.4 on 2023-08-27 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizess', '0005_defoulmultitquiz_defoultquiz_ball_draganddrop_ball_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='not_actioned_users',
            field=models.ManyToManyField(related_name='tasks_not_actioned', to=settings.AUTH_USER_MODEL),
        ),
    ]
