# Generated by Django 4.2.4 on 2023-08-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizess', '0007_closedtest_alter_defoulmultitquiz_author_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedtest',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='defoulmultitquiz',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='defoultquiz',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
