# Generated by Django 4.1.3 on 2023-04-02 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=4)),
                ('url', models.SlugField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('max_students', models.IntegerField(default=24)),
                ('ball', models.FloatField(default=0.0)),
                ('active_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_active_user', to=settings.AUTH_USER_MODEL)),
                ('author_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_author', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='class_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
