# Generated by Django 4.1.3 on 2023-03-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
