# Generated by Django 4.2.4 on 2023-09-10 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olimpiads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olimpiada',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ol_solves', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ol_solve_problems', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
