# Generated by Django 4.2.4 on 2023-08-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masalalar', '0006_alter_masala_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testlar',
            old_name='_in',
            new_name='t_in',
        ),
    ]
