# Generated by Django 4.2.4 on 2023-08-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masalalar', '0007_rename__in_testlar_t_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='urinish',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
