# Generated by Django 4.2.4 on 2023-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masalalar', '0008_urinish_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelar',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default=1, max_length=3234),
            preserve_default=False,
        ),
    ]
