# Generated by Django 4.2.4 on 2023-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masalalar', '0010_alter_urinish_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='masala',
            name='have_yechim',
            field=models.BooleanField(default=False),
        ),
    ]
